--- # Task File for Apache

- name: Install apache
  yum:
    name: httpd
    state: latest

- name: Copy httpd.conf template
  template: 
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart httpd

- name: Enable and Start the Service
  service: 
    name: httpd
    enabled: yes
    state: started 


