--- # testing the J2 Template Module
- hosts: all
  connection: ssh
  user: yahoo
  sudo: yes
  gather_facts: yes
  vars: 
    user: this
    password: thisismyworld
    connectionType: SFTP
  tasks: 
  - name: Install the configuration file custmized for the system
    template: 
      src: test.config.j2
      dest: /home/yahoo/test.config  
      owner: yahoo
      group: yahoo
      mode: 750
  

