--- # Tags PLAYBOOK Example
- hosts: local
  user: yahoo
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install telnet
      yum:
        name: telnet
        state: present
      tags:
        - always
