--- 
- hosts: all 
  user: "{{non_root_user}}"
  become: "{{ansible_become}}"
  connection: "{{ansible_connection}}"
  gather_facts: yes

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_users:
      - "{{non_root_user}}"


  roles:
    - geerlingguy.docker
