--- 
- hosts: cluster

  
  tasks:
  - name: Set the IPtables value to 1
    shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes 
