---
- hosts: node
  become: yes

  tasks:
    - name: install container-selinux dependency
      yum:
       name: container-selinux
       enablerepo: rhui-REGION-rhel-server-extras
       state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
   # - name: install container-selinux 
   #   yum:
   #    name: container-selinux
   #    state: present
   #   when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
