--- # VARIABLES AT A COMMAND LINE PASSING EXAMPLE
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  gather_facts: no
 
  tasks: 
  - name: INstall some package
    yum: 
      name: '{{ me }}'
      state: latest
