--- # LOCAL ACTION DEMO
- hosts: node
  user: yahoo
  sudo: yes
  connection: ssh
  gather_facts: no
  
  tasks: 
  - name: Ping the node server befor we run our install
    local_action: command ping -c 4 34.229.241.19
  - name: Install the httpd on the remote server
    yum:
      name: httpd
      state: latest
