--- # NOTIFY Playbook translation
- hosts: local
  user: yahoo
  sudo: yes
  gather_facts: no
  
  tasks:
  - name: Install HTTPD AppServer
    yum:
      name: httpd
      state: installed
    notify:
    - Restart HTTPD
 
  handlers:
   - name: Restart HTTPD
     action: service name=httpd state=restarted





