---
- hosts: all
  become: yes

  tasks:
    - name: Install EPEL-REPO
      yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Ansible
      yum:
        name: ansible
        state: present
      when: ansible_os_family == "RedHat"
