--- # Prompt PLAYBOOK Example
- hosts: local
  user: yahoo
  sudo: yes
  connection: ssh
  gather_facts: no

  vars_prompt:
    - name: pkgtoinstall
      prompt: Which Package to Install 
      default: telnet
      private: no

  tasks:
    - name: Install the "{{pkgtoinstall}}" package
      yum:
        name: "{{pkgtoinstall}}" 
        state: latest
