--- # RUNONCE Playbook Example
- hosts: all        # target section
  user: yahoo       # who can use this playbook on Remote Server
  sudo: yes         # running with sudo rights
  connection: ssh   # ssh or paramiko
  gather_facts: no  # if we want to use one of the environment variables

  tasks: 
    - name: Run the uptime command on all hosts and login
      raw: /usr/bin/uptime >> /home/yahoo/uptime.log

    - name: List the ar Dir and log it
      raw: ls -la /var >> /home/yahoo/dir.list
      run_once: true     # this will run only once on the first server in the inventory list
