--- # StartAt Playbook example
- hosts: local
  user: yahoo
  become: yes
  connection: ssh
  gather_facts: no
  
  tasks: 
  - name: INstall telnet
    yum: 
      name: telnet
      state: latest
  - name: Install Httpd
    yum:
      name: httpd
      state: latest
  - name: LIST HOME
    command: ls -la /home/yahoo
    register: result
  - debug: 
      var:  result

