--- # Outline to Playbook translation
- hosts: local
  user: yahoo
  sudo: yes
  gather_facts: no
  
  tasks:
  - name: date/time stamp of when the playbook starts
    command: /usr/bin/date
    register: timestamp_start
  - debug: 
      var: timestamp_start
  - name: Install HTTPD AppServer
    yum:
      name: httpd
      state: installed
    notify:
    - Restart HTTPD

  - name: Install client software - telnet
    yum: 
      name: telnet 
      state: latest
  
  - name: Log all the packages install on the system
    command: yum list installed 
    register: installed_result
  - debug: 
      var: installed_result
  
  - name:  date/time stamp for when the playbook ends
    command: /usr/bin/date 
    register: timestamp_end
  - debug: 
      var: timestamp_end
 
  handlers:
   - name: Restart HTTPD
     action: service name=httpd state=restarted





