---  # the APT  Module -------
- hosts: node
  sudo: yes
  user: yahoo
  connection: ssh
  gather_facts: no

  tasks:
  - name: Install HTTPD
    apt:
      name: apache2
      state: present

  - name: Remove
    apt:
      name: apache2
      state: absent

  - name: Eq to apt-get update
    apt: update_cache=yes
      
  - name: Eq to apt-get upgrade
    apt: upgrade=dist

