---  # the waitfor Module -------
- hosts: node
  sudo: yes
  gather_facts: no
  tasks:
  - name: Install HTTPD
    yum:
      name: tomcat
      state: latest
  - name: Wait for POrt 8080 to Listen
    wait_for: 
      port: 8080
      state: started
  - name: Verify tree installation
    yum:
      name: tree
      state: latest
